# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e7ce90a385ec196b95e0445b5f5af3822fd1f9517e9fa099480cdce6b8ad9494f0fd61fa01a813e1aba45799057eddc0f8472cc3c066737e7f3cd1c4fe935f8a

test:
  secret_key_base: ba4338be9ab5ee69c24e9e1b96c4573838a2f9bb90cdcf7b7005aef89840372c8f46c5cbcce4c8f5be4e2897a6b2148c956d6c3acc94c42ccae6706adfb4dd46

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
